### ISSUE TITLE
Jump to the Last Edit Location, regardless of the file.

### ISSUE THREAD

**Issue by Bost** [emacs-evil/goto-chg#11]
We wrote a package just to solve the stated problem. See https://github.com/Bost/jump-last/blob/master/jump-last.el 
It's getting pretty small & neat, so maybe is better to integrate our code into your package. What do you think?

**Comment by wasamasa** [comment]
This package wouldn't even manage to be included into MELPA, so no.

**Comment by Bost** [comment]
> This package wouldn't even manage to be included into MELPA, so no.

Who's saying I intend to make it available on MELPA??? The contrary is true. 
The code works for me as it is and I'm definitely not going to waste my time on polishing a few lines of code just for the sake of it.
I was telling you, if you want to have such a feature then I'd step out and do it. However from the tone of your response, I'm getting the impression giving you such an offer was a mistake.
