### ISSUE TITLE
recentering breaks goto-last-change sequence

### ISSUE THREAD

**Issue by ahihi** [emacs-evil/goto-chg#17]
i am often trying to recenter the point between calls to `goto-last-change`, but this breaks the change sequence and takes me back to the most recent change.

i suspect this would happen with many other commands too. would it be feasible to detect when commands neither edit the buffer nor move point, and prevent these from breaking the sequence? or perhaps add a configuration option to manually specify such commands?

steps to reproduce:

- have a buffer with at least 3 changes
- run `goto-last-change` twice - point is at 2nd most recent change
- run `recenter` or `recenter-top-bottom`
- run `goto-last-change` - point is back at the most recent change, instead of the 3rd most recent

**Comment by wasamasa** [comment]
Sorry, but I will not implement this.

The code is already complicated enough and I can barely make sense of it. Making it even more complicated for what is essentially one big gross hack relying on the undo chain is a bad idea. Instead, I propose discussion on emacs-devel how to add functionality to Emacs that makes tracking change positions easier (IIRC the topic did come up before, but no fruitful discussion came of this).
