### ISSUE TITLE
Comments created via comment-dwim not detected as changes

### ISSUE THREAD

**Issue by betaprior** [emacs-evil/goto-chg#8]
To reproduce: mark a line and comment via M-x comment-dwim. It is expected that this will be the last change for goto-chg, however goto-chg ignores this action and keeps going to the latest change where actual typing took place.

**Comment by wasamasa** [comment]
I cannot reproduce from that information alone. Make a step by step repro, with helpful ASCII art showing positions of point, what you expect and what you got.

**Comment by betaprior** [comment]
Here is a repro on a vanilla emacs setup with only goto-chg and undo-tree loaded. Observe that in the first case goto-chg fails to register comment as change.

Version info: Emacs 28.0.50, undo-tree 0.7.4, goto-chg 1.7.3

![goto-chg-bug](https://user-images.githubusercontent.com/338250/83367401-2c660b00-a369-11ea-9845-db36510b1b6c.gif)

**Comment by wasamasa** [comment]
I cannot reproduce that with Emacs 26.3. On the master branch however (see the orange thing in the mode line) I can. Chances are that something on master broke this barely functional package. Here's my repro for both versions and the values of `buffer-undo-list`, with 26.3 on top and master at the bottom:

![20200603_201445](https://user-images.githubusercontent.com/3588994/83672683-ed3cf180-a5d6-11ea-9c00-fb0b06e6a98b.png)
![20200603_201446](https://user-images.githubusercontent.com/3588994/83672685-ef06b500-a5d6-11ea-99e3-c6acce2820e2.png)

**Comment by wasamasa** [comment]
As expected, there was a change on master, comment-dwim uses `combine-change-calls` resulting in that funny `undo-list` entry with `undo--wrap-and-run-primitive-undo`. Its last element resembles the one we need, so I wrote a hack detecting such entries and replacing them with the last item's range. This is a terrible hack, but it seems to resolve your issue. Can you please confirm whether it works for you?

Now, if you really want to do me a favor, consider reporting a bug or starting a discussion on emacs-devel how this kind of usage can be better supported by Emacs because the undo list is definitely not made for other things than undoing. Otherwise I suspect a future Emacs release will kill off this package for good...

**Comment by betaprior** [comment]
@wasamasa thank you, it looks like the fix works! But I think I'm out of my depth addressing this on emacs-devel, not knowing anything about how undo is supposed to work and what exactly they did to break the package. I am willing to testify that goto-chg is the only navigation package of the many I've tried that actually does its job predictably and intuitively, and it would be a terrible shame if it got broken upstream.

**Comment by wasamasa** [comment]
It's not about undo being wrong, it's about using `undo-list` for non-undo things being a fundamental mismatch. The intention of `undo-list` is to undo things, not to guess what the buffer positions of the related changes are without ever performing these undo steps (which is what this package tries to do). As soon as an undo-entry tells you to execute a particular function to perform an undo, this means you can no longer reliably guess the position before that change. In this particular case I've managed to do this as Emacs has been nice enough to store that information, but there's no guarantee that this will always be the case. Therefore I believe there's merit in a general discussion how a better approach would look like that doesn't rely on how undo information is stored for a buffer.

**Comment by taquangtrung** [comment]
I encountered the same problem that `goto-last-change` cannot jump to the location commented by `comment-dwim-2`.

@wasamasa: can you help to check?

I'm using the newest `comment-dwim-2`, version 1.4.3, released on 20210101.1820, and the newest `goto-chg`, version 1.7.5, released on 20220107.1733.

**Comment by wasamasa** [comment]
This is not the same problem (comment-dwim is one thing, an external package another one). Create a new issue, provide all information (Emacs version is lacking), provide minimized reproduction instructions, then we'll talk.
